name: Rollback on Develop

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Número do hash do commit'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rollback
        run: |
          # Obtém o número do hash do commit fornecido
          COMMIT_HASH=${{ github.event.inputs.commit_hash }}

          # Reverte para o commit especificado
          git revert --no-commit $COMMIT_HASH..HEAD
          git commit -m "Rollback to $COMMIT_HASH"

          # Empurra as alterações revertidas
          git push origin main
