name: Rollback on Develop

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Número do hash do commit'
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Rollback
        run: |
          # Obtém o número do hash do commit fornecido
          COMMIT_HASH=${{ github.event.inputs.commit_hash }}

          # Reverte para o commit especificado usando git reset
          git revert --hard $COMMIT_HASH

          # Empurra as alterações revertidas
          git push --force origin develop
